/**
  * @async Match Actions
  */
export const FETCH_MATCHES_INIT = 'FETCH_MATCHES_INIT'
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS'
export const FETCH_MATCHES_FAILURE = 'FETCH_MATCHES_FAILURE'
export const FETCH_MATCH_INIT = 'FETCH_MATCH_INIT'
export const FETCH_MATCH_SUCCESS = 'FETCH_MATCH_SUCCESS'
export const FETCH_MATCH_FAILURE = 'FETCH_MATCH_FAILURE'
export const SAVE_MATCH_INIT = 'SAVE_MATCH_INIT'
export const SAVE_MATCH_SUCCESS = 'SAVE_MATCH_SUCCESS'
export const SAVE_MATCH_FAILURE = 'SAVE_MATCH_FAILURE'
